version: "3.7"

services:
    gui:
        image: yourimagename/gui
        build:
            context: gui/
        ports:
        - 8080:8080
        depends_on: 
        - redis
    # lex:
    #     image: yourimagename/lex
    #     build:
    #         context: lex
    #     ports:
    #     - 5000:5000

# from your apps you can reach Redis IP with its fqdn "redis"
    redis:
        image: redis
        ports:
        - 6379:6379
        